# Generated by Django 5.2.8 on 2025-11-21 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Restaurant Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('cuisine_type', models.CharField(choices=[('ITALIAN', 'Italian'), ('CHINESE', 'Chinese'), ('INDIAN', 'Indian'), ('MALAY', 'Malay'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('THAI', 'Thai'), ('WESTERN', 'Western'), ('FAST_FOOD', 'Fast Food'), ('SEAFOOD', 'Seafood'), ('VEGETARIAN', 'Vegetarian'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Cuisine Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'RESTAURANT_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (RM)')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN', 'Main Course'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage'), ('SIDE', 'Side Dish')], default='MAIN', max_length=20, verbose_name='Category')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
