# Generated by Django 5.2.8 on 2025-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('APPETIZERS', 'Appetizers'), ('MAIN_COURSE', 'Main Course'), ('DESSERTS', 'Desserts'), ('BEVERAGES', 'Beverages'), ('SIDES', 'Sides')], default='MAIN_COURSE', max_length=20, verbose_name='Category'),
        ),
    ]
