# Generated by Django 5.2.8 on 2025-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Is Open'),
        ),
    ]
