# Generated by Django 5.2.8 on 2026-01-04 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_delivery_time_restaurant_is_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5 stars)')),
                ('comment', models.TextField(blank=True, verbose_name='Review Comment')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='User has ordered this specific menu item', verbose_name='Verified Purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.menuitem')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Item Review',
                'verbose_name_plural': 'Menu Item Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['menu_item', '-created_at'], name='restaurants_menu_it_188a44_idx'), models.Index(fields=['user'], name='restaurants_user_id_96f16f_idx'), models.Index(fields=['rating'], name='restaurants_rating_51d6c0_idx')],
                'unique_together': {('menu_item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5 stars)')),
                ('comment', models.TextField(blank=True, verbose_name='Review Comment')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='User has completed at least one order from this restaurant', verbose_name='Verified Purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Review',
                'verbose_name_plural': 'Restaurant Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='restaurants_restaur_a7ce0e_idx'), models.Index(fields=['user'], name='restaurants_user_id_8cf4ba_idx'), models.Index(fields=['rating'], name='restaurants_rating_c25f10_idx')],
                'unique_together': {('restaurant', 'user')},
            },
        ),
    ]
